@host=http://localhost:3000/auth/test


@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjAyMTg0MTUyLCJleHAiOjE2MDIxODU5NTJ9.yAAfEJn2mhlj5kPnReoCZj5yE67IetiMMzSKMpKPXOo

# @name test
GET {{host}} HTTP/1.1
Authorization: Bearer {{authToken}}
